<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="DatabaseComunications\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GrafikPlanerData\GrafikPlanerData.csproj" />
    </ItemGroup>

</Project>
